### ISSUE TITLE
Context

### ISSUE THREAD

**Issue by alanhoff** [pateketrueke/json-schema-faker#43] opened 2015-05-27 16:26 UTC
Hello there, how can I assign contexts to my schemas? I would like to do something like this:

```javascript
{
  id: 'hello-world',
  properties: {
    id: {
      $ref: '#/context/query/id'
    }
  },
  context: {
    query: {
      id: 80
    }
  }
}
```

**Comment by pateketrueke** [comment] 2015-05-27 16:58
Which output do you expect?

**Comment by alanhoff** [comment] 2015-05-27 17:14
```javascript
{
  id: 80
}
```

**Comment by tkoomzaaskz** [comment] 2015-05-27 18:01
@alanhoff could you explain, particularly, what might be the use of such thing?

**Comment by alanhoff** [comment] 2015-05-27 18:19
i'd built a Hapi plugin that uses JSF to reply with fake data, and would be awesome if i could reference the current request's context (aka body, params, query, headers, etc..)

https://github.com/alanhoff/node-hapi-faker

**Comment by pateketrueke** [comment] 2015-05-27 18:57
You must follow the json-schema rules for that, the `context` property is not standard.

```json
{
  "id": "hello-world",
  "type": "object",
  "definitions": {
    "queryId": {
      "type": "integer",
      "minimum": 0,
      "maximum": 80
    }
  },
  "properties": {
    "id": {
      "$ref": "#/definitions/queryId"
    }
  },
  "required": ["id"]
}
```

But you can't produce any fixed value for `queryId` yet.

**Comment by tkoomzaaskz** [comment] 2015-05-27 19:14
Correct me if I'm wrong, but couldn't he define an enum with just a single element to choose from? That's not what json-schema schema was designed for, however...

**Comment by pateketrueke** [comment] 2015-05-27 19:20
You're absolutely right!

Using `enum` does the trick.

> That's not what json-schema schema was designed for, however...

Totally agree...

**Comment by tkoomzaaskz** [comment] 2015-05-27 21:25
@alanhoff can we help you anyhow or shall we close that one?
@pateketrueke we might add info about adding fixed values to the docs, however (with a note like "if you really need to").

PS I just thought of another solution for this - using regexp. There is randexp used below JSF. If you give him a hardcoded string, you'll surely get that string ;)

**Comment by ducin** [comment] 2015-06-11 14:52
I'm closing this one, since nothing is happening and the question has been answered.

**Closed by ducin** 2015-06-11 14:52 UTC
